FROM quay.io/openshift/ci:ocp_4.20_cli
RUN <<run-EOF
set -exo pipefail; shopt -s inherit_errexit
typeset binDir=/usr/local/bin
# Install openssh-clients, jq.
typeset -a pkgs=(openssh-clients jq)
if command -v dnf &> /dev/null; then \
    dnf install --setopt tsflags=nodocs -y "${pkgs[@]}"
    dnf clean all; \
else \
    microdnf install -y "${pkgs[@]}"
    microdnf clean all; \
fi
rm -rf /var/cache/dnf/*
# Install yq.
{
    wget -qO "${binDir}/yq" \
        "https://github.com/mikefarah/yq/releases/latest/download/yq_$(
            uname -s | tr '[:upper:]' '[:lower:]'
        )_$(
            uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/'
        )" &&
    chmod a+x "${binDir}/yq"
}
# Install virtctl.
{
    wget -qO "${binDir}/virtctl"  "$(
        wget -qO - 'https://api.github.com/repos/kubevirt/kubevirt/releases/latest' |
        jq -r \
            --arg os "$(uname -s | tr '[:upper:]' '[:lower:]')" \
            --arg cpu "$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')" \
            '.tag_name as $tag | .assets[] | select(.name=="virtctl-\($tag)-\($os)-\($cpu)").browser_download_url'
    )"
    chmod a+x "${binDir}/virtctl"
}
run-EOF
